name: bioreino_mobile
description: Plataforma de cursos online de biologia.
publish_to: "none"
version: 1.0.2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^2.0.0
  mongo_dart: ^0.10.3
  shared_preferences: ^2.3.2
  flutter_cache_manager: ^3.4.1
  bcrypt: ^1.1.3
  youtube_player_flutter: ^9.0.4
  intl: ^0.19.0
  url_launcher: ^6.3.0
  dio: ^5.7.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  decimal: ^2.2.0

flutter_icons:
  android: true
  min_sdk_android: 19
  image_path: "assets/launcher/play_store_512.png"
  adaptive_icon_foreground: "assets/launcher/play_store_512.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/drawer_icons/
    - assets/launcher/
    - assets/
    - assets/splash_screen_icons/
    - assets/error_images/
    - assets/lessons_icons/
    - assets/home_images/
    - assets/login_images/
